### ISSUE TITLE
examples of usage

### ISSUE THREAD

**Issue by jbenet** [ipfs/scala-ipfs-api#1]
would be great to have extensive examples of usage in the readme, like https://github.com/ipfs/node-ipfs-api

**Comment by cboddy** [comment]
Excellent suggestion, and one I also had in mind for Scala and Java, after the remaining API calls are implemented :-)

**Comment by cboddy** [comment]
I've fleshed out some examples and built a  java-doc site on github-pages, both are linked to from  the README, more examples to come.

**Comment by jbenet** [comment]
:+1:
